// const BASE_URL = 'http://ec2-13-60-19-67.eu-north-1.compute.amazonaws.com'
// const BASE_URL = 'https://13.60.19.67'
const BASE_URL = 'https://localhost'
// const BASE_URL = 'https://api.kanbantastisch.xyz'
// const BASE_URL = 'kanbantastisch-backend.xyz'
const BASE_PORT = '8443'
const ROUTE_BOARDS = 'boards'